### ISSUE TITLE
run model_attention.py

### ISSUE THREAD

**Issue by niu1970** [tuyunbin/Video-Description-with-Spatial-Temporal-Attention#13]
D:\Anaconda2\envs\Theano\python.exe D:/PythonCode/Video-Description-with-Spatial-Temporal-Attention-master/train_model.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda2\envs\Theano\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "D:\Anaconda2\envs\Theano\lib\multiprocessing\forking.py", line 510, in prepare
    '__parents_main__', file, path_name, etc
  File "D:\PythonCode\Video-Description-with-Spatial-Temporal-Attention-master\train_model.py", line 8, in <module>
    import model_attention
  File "D:\PythonCode\Video-Description-with-Spatial-Temporal-Attention-master\model_attention.py", line 21, in <module>
    import metrics
  File "D:\PythonCode\Video-Description-with-Spatial-Temporal-Attention-master\metrics.py", line 74, in <module>
    manager = Manager()
  File "D:\Anaconda2\envs\Theano\lib\multiprocessing\__init__.py", line 99, in Manager
    m.start()
  File "D:\Anaconda2\envs\Theano\lib\multiprocessing\managers.py", line 524, in start
    self._process.start()
  File "D:\Anaconda2\envs\Theano\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "D:\Anaconda2\envs\Theano\lib\multiprocessing\forking.py", line 258, in __init__
    cmd = get_command_line() + [rhandle]
  File "D:\Anaconda2\envs\Theano\lib\multiprocessing\forking.py", line 358, in get_command_line
    is not going to be frozen to produce a Windows executable.''')
RuntimeError: 
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
Traceback (most recent call last):
  File "D:/PythonCode/Video-Description-with-Spatial-Temporal-Attention-master/train_model.py", line 8, in <module>
    import model_attention
  File "D:\PythonCode\Video-Description-with-Spatial-Temporal-Attention-master\model_attention.py", line 21, in <module>
    import metrics
  File "D:\PythonCode\Video-Description-with-Spatial-Temporal-Attention-master\metrics.py", line 74, in <module>
    manager = Manager()
  File "D:\Anaconda2\envs\Theano\lib\multiprocessing\__init__.py", line 99, in Manager
    m.start()
  File "D:\Anaconda2\envs\Theano\lib\multiprocessing\managers.py", line 528, in start
    self._address = reader.recv()
EOFError

Process finished with exit code 1
![image](https://user-images.githubusercontent.com/62270710/82977544-c7cb4900-a014-11ea-9c00-c973de8cd388.png)

**Comment by niu1970** [comment]
![image](https://user-images.githubusercontent.com/62270710/82977661-1b3d9700-a015-11ea-880e-8a93e0de1ad3.png)

![image](https://user-images.githubusercontent.com/62270710/82977709-3f00dd00-a015-11ea-9de3-4c253f142040.png)

![image](https://user-images.githubusercontent.com/62270710/82977739-58098e00-a015-11ea-85be-c5f253ae7364.png)

**Comment by tuyunbin** [comment]
This project is implemented on linux system, and you should use linux as well.

**Comment by niu1970** [comment]
Good!I'll try, thank you!Could you please tell me the general environment configuration?

**Comment by tuyunbin** [comment]
You can use Ubuntu 16+, python=2.7, and a GPU like Titan X.

**Comment by niu1970** [comment]
Thank you!
